#!zsh

(
local NSFSH
local dir
local arch=`gcc -dumpmachine`

local emergency_copy=/common/linux/appl/handloom
if [[ -z $SILISTIX_HOME && -d $emergency_copy ]]; then
    export SILISTIX_HOME=$emergency_copy
    echo "-- Defaulting SILISTIX_HOME to $SILISTIX_HOME" >&2
fi

if [[ -z $SILISTIX_HOME ]]; then
    echo "Despite my best efforts, I still can't find a home for silistix." >&2 # '"
    return 1
fi

if [[ -z $NSFSH ]]; then
    NSFSH=$SILISTIX_HOME/bin/nsfsh
fi

if [[ ! -x $NSFSH ]]; then
    echo "$SILISTIX_HOME/bin lacks a shell" >&2
    return 1
fi

echo "-- Running $NSFSH" >&2

$NSFSH "$@"
)
